trigger: none

pool: 
  vmImage: 'ubuntu-latest'
stages:
- stage: 
  jobs:
    - job: 
      steps:
      - task: TerraformTaskV4@4
        inputs:
          provider: 'azurerm'
          command: 'init'
          backendServiceArm: 'Azure subscription 1(9117002a-2308-428d-993b-9f46dfdfd10c)'
          backendAzureRmResourceGroupName: 'infra-rg'
          backendAzureRmStorageAccountName: 'mystorageaccount199546'
          backendAzureRmContainerName: 'mycontainer'
          backendAzureRmKey: 'terraform.tfstate'
      - task: TerraformTaskV4@4
        inputs:
          provider: 'azurerm'
          command: 'validate'
      